---
title: "R Markdown Workshop"
output: 
  html_document:
    toc: FALSE
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

&nbsp;

[Introduction to R Markdown](slides/) (slides)

## R Markdown quick start

[cheetsheet](slides/index.html#5)


## Exercises
Output Type | Instructions | Resources / Notes
-------- | ---------- | --------------------------------------
R Notebooks | [Get Started](notebooks.html) | Start practicing your literate coding
**Slide** Decks | [Get Started](dukeslides_getstarted.html) | [DukeSlides](https://www.johnlittle.info/dukeslides/) (A [xaringan](https://slides.yihui.name/xaringan/#1) implementation)
MS Word | [Get Started](msword_getstarted.html) | Use `knitr::kable(df)` for [dataframe](https://bookdown.org/yihui/rmarkdown/html-document.html#data-frame-printing) printing
Dashboards | [Get Started](dashboards.html) | [flexdashboard](https://rmarkdown.rstudio.com/flexdashboard/)
Websites | [Get Started](blogdown_getstarted.html) | [Blogdown](blogdown_getstarted.html)
PDF | [Get Started](pdf_getstarted.html) | May need to install https://yihui.name/tinytex/<br> `install.packages('tinytex')` <br> `tinytex::install_tinytex()`
Book | [Get Started](https://bookdown.org/yihui/bookdown/get-started.html) | [Bookdown](https://bookdown.org/yihui/bookdown/)<br>May need to install https://yihui.name/tinytex/<br> `install.packages('tinytex')` <br> `tinytex::install_tinytex()`

## Learn More

[R Markdown: The Definitive Guide book](https://bookdown.org/yihui/rmarkdown/) by *Yihui Xie, J. J. Allaire, Garrett Grolemund*
