# COMMENT: redirect rules with all the fields expanded
# According to netlify domain management
# https://app.netlify.com/sites/rmarkdown-rfun/settings/domain#custom-domains
# Redirect default Netlify subdomain to primary domain
# https://rmarkdown-rfun.netlify.com/* https://rmarkdown.library.duke.edu/:splat 301!
[[redirects]]
  from = "https://rmarkdown-rfun.netlify.com/*"
  to = "https://rmarkdown.library.duke.edu/:splat"
  status = 301
  force = true
